version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8 # Ensure this matches your project's Python version
    commands:
      - echo Installing dependencies...
      - pip install --upgrade pip setuptools wheel
      - pip install numpy cython
  pre_build:
    commands:
      - echo Prebuild operations
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the application
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
