version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10 
    commands:
      - echo "Installing system dependencies..."
      - apt-get update && apt-get install -y build-essential
      - echo "Upgrading pip, setuptools, and wheel..."
      - pip install --upgrade pip setuptools wheel
      - echo "Installing numpy and cython..."
      - pip install numpy
  pre_build:
    commands:
      - echo Prebuild operations
      - pip install -r requirements.txt
  build:
    commands:
      - echo Building the application
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - "**/*"
